/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManualEditarRouteImport } from './routes/manual.editar'
import { Route as LinhaDoTempoEditarRouteImport } from './routes/linha-do-tempo.editar'
import { Route as HistoriaEditarRouteImport } from './routes/historia.editar'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualEditarRoute = ManualEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ManualRoute,
} as any)
const LinhaDoTempoEditarRoute = LinhaDoTempoEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => LinhaDoTempoRoute,
} as any)
const HistoriaEditarRoute = HistoriaEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => HistoriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/historia': typeof HistoriaRouteWithChildren
  '/linha-do-tempo': typeof LinhaDoTempoRouteWithChildren
  '/manual': typeof ManualRouteWithChildren
  '/painel': typeof PainelRoute
  '/historia/editar': typeof HistoriaEditarRoute
  '/linha-do-tempo/editar': typeof LinhaDoTempoEditarRoute
  '/manual/editar': typeof ManualEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/historia': typeof HistoriaRouteWithChildren
  '/linha-do-tempo': typeof LinhaDoTempoRouteWithChildren
  '/manual': typeof ManualRouteWithChildren
  '/painel': typeof PainelRoute
  '/historia/editar': typeof HistoriaEditarRoute
  '/linha-do-tempo/editar': typeof LinhaDoTempoEditarRoute
  '/manual/editar': typeof ManualEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album': typeof AlbumRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRoute
  '/historia': typeof HistoriaRouteWithChildren
  '/linha-do-tempo': typeof LinhaDoTempoRouteWithChildren
  '/manual': typeof ManualRouteWithChildren
  '/painel': typeof PainelRoute
  '/historia/editar': typeof HistoriaEditarRoute
  '/linha-do-tempo/editar': typeof LinhaDoTempoEditarRoute
  '/manual/editar': typeof ManualEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album'
    | '/auth'
    | '/editor'
    | '/historia'
    | '/linha-do-tempo'
    | '/manual'
    | '/painel'
    | '/historia/editar'
    | '/linha-do-tempo/editar'
    | '/manual/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/auth'
    | '/editor'
    | '/historia'
    | '/linha-do-tempo'
    | '/manual'
    | '/painel'
    | '/historia/editar'
    | '/linha-do-tempo/editar'
    | '/manual/editar'
  id:
    | '__root__'
    | '/'
    | '/album'
    | '/auth'
    | '/editor'
    | '/historia'
    | '/linha-do-tempo'
    | '/manual'
    | '/painel'
    | '/historia/editar'
    | '/linha-do-tempo/editar'
    | '/manual/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumRoute: typeof AlbumRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRoute
  HistoriaRoute: typeof HistoriaRouteWithChildren
  LinhaDoTempoRoute: typeof LinhaDoTempoRouteWithChildren
  ManualRoute: typeof ManualRouteWithChildren
  PainelRoute: typeof PainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/editar': {
      id: '/manual/editar'
      path: '/editar'
      fullPath: '/manual/editar'
      preLoaderRoute: typeof ManualEditarRouteImport
      parentRoute: typeof ManualRoute
    }
    '/linha-do-tempo/editar': {
      id: '/linha-do-tempo/editar'
      path: '/editar'
      fullPath: '/linha-do-tempo/editar'
      preLoaderRoute: typeof LinhaDoTempoEditarRouteImport
      parentRoute: typeof LinhaDoTempoRoute
    }
    '/historia/editar': {
      id: '/historia/editar'
      path: '/editar'
      fullPath: '/historia/editar'
      preLoaderRoute: typeof HistoriaEditarRouteImport
      parentRoute: typeof HistoriaRoute
    }
  }
}

interface HistoriaRouteChildren {
  HistoriaEditarRoute: typeof HistoriaEditarRoute
}

const HistoriaRouteChildren: HistoriaRouteChildren = {
  HistoriaEditarRoute: HistoriaEditarRoute,
}

const HistoriaRouteWithChildren = HistoriaRoute._addFileChildren(
  HistoriaRouteChildren,
)

interface LinhaDoTempoRouteChildren {
  LinhaDoTempoEditarRoute: typeof LinhaDoTempoEditarRoute
}

const LinhaDoTempoRouteChildren: LinhaDoTempoRouteChildren = {
  LinhaDoTempoEditarRoute: LinhaDoTempoEditarRoute,
}

const LinhaDoTempoRouteWithChildren = LinhaDoTempoRoute._addFileChildren(
  LinhaDoTempoRouteChildren,
)

interface ManualRouteChildren {
  ManualEditarRoute: typeof ManualEditarRoute
}

const ManualRouteChildren: ManualRouteChildren = {
  ManualEditarRoute: ManualEditarRoute,
}

const ManualRouteWithChildren =
  ManualRoute._addFileChildren(ManualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumRoute: AlbumRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRoute,
  HistoriaRoute: HistoriaRouteWithChildren,
  LinhaDoTempoRoute: LinhaDoTempoRouteWithChildren,
  ManualRoute: ManualRouteWithChildren,
  PainelRoute: PainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
